# Generated by Django 3.2.19 on 2023-06-18 09:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downwarddog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video')),
            ],
        ),
    ]
