# Generated by Django 3.2.19 on 2023-07-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downwarddog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['status'], 'verbose_name_plural': 'Classes'},
        ),
    ]
