# Generated by Django 3.2.19 on 2023-06-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downwarddog', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
