# Generated by Django 3.2.19 on 2023-07-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downwarddog', '0002_alter_classes_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_class',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='available_time',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('classes', 'user'), name='unique_booking'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('classes', 'available_date'), name='unique_class'),
        ),
    ]
